// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: api/proto/listing/listing.proto

package listing_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_api_proto_listing_listing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_listing_listing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_api_proto_listing_listing_proto_rawDescGZIP(), []int{0}
}

type CreateListingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`             // <--- ДОБАВЛЕНО (ID пользователя, создающего объявление)
	CategoryId    string                 `protobuf:"bytes,2,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"` // <--- ДОБАВЛЕНО
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Price         float64                `protobuf:"fixed64,5,opt,name=price,proto3" json:"price,omitempty"` // repeated string photos = 6; // Если фото можно загружать сразу при создании
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateListingRequest) Reset() {
	*x = CreateListingRequest{}
	mi := &file_api_proto_listing_listing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateListingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateListingRequest) ProtoMessage() {}

func (x *CreateListingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_listing_listing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateListingRequest.ProtoReflect.Descriptor instead.
func (*CreateListingRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_listing_listing_proto_rawDescGZIP(), []int{1}
}

func (x *CreateListingRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateListingRequest) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

func (x *CreateListingRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateListingRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateListingRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type UpdateListingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`             // <--- ДОБАВЛЕНО (ID пользователя, пытающегося обновить)
	CategoryId    string                 `protobuf:"bytes,3,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"` // <--- ДОБАВЛЕНО (Если категорию можно менять)
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Price         float64                `protobuf:"fixed64,6,opt,name=price,proto3" json:"price,omitempty"`
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"` // Рассмотри использование enum для статуса
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateListingRequest) Reset() {
	*x = UpdateListingRequest{}
	mi := &file_api_proto_listing_listing_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateListingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateListingRequest) ProtoMessage() {}

func (x *UpdateListingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_listing_listing_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateListingRequest.ProtoReflect.Descriptor instead.
func (*UpdateListingRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_listing_listing_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateListingRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateListingRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateListingRequest) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

func (x *UpdateListingRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateListingRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateListingRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *UpdateListingRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type DeleteListingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // <--- ДОБАВЛЕНО (ID пользователя, пытающегося удалить)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteListingRequest) Reset() {
	*x = DeleteListingRequest{}
	mi := &file_api_proto_listing_listing_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteListingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteListingRequest) ProtoMessage() {}

func (x *DeleteListingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_listing_listing_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteListingRequest.ProtoReflect.Descriptor instead.
func (*DeleteListingRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_listing_listing_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteListingRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteListingRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetListingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetListingRequest) Reset() {
	*x = GetListingRequest{}
	mi := &file_api_proto_listing_listing_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetListingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListingRequest) ProtoMessage() {}

func (x *GetListingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_listing_listing_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListingRequest.ProtoReflect.Descriptor instead.
func (*GetListingRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_listing_listing_proto_rawDescGZIP(), []int{4}
}

func (x *GetListingRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`             // <--- ДОБАВЛЕНО
	CategoryId    string                 `protobuf:"bytes,3,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"` // <--- ДОБАВЛЕНО
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Price         float64                `protobuf:"fixed64,6,opt,name=price,proto3" json:"price,omitempty"`
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"` // Рассмотри использование enum для статуса
	Photos        []string               `protobuf:"bytes,8,rep,name=photos,proto3" json:"photos,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`  // <--- ИЗМЕНЕНО НА Timestamp
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"` // <--- ИЗМЕНЕНО НА Timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListingResponse) Reset() {
	*x = ListingResponse{}
	mi := &file_api_proto_listing_listing_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListingResponse) ProtoMessage() {}

func (x *ListingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_listing_listing_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListingResponse.ProtoReflect.Descriptor instead.
func (*ListingResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_listing_listing_proto_rawDescGZIP(), []int{5}
}

func (x *ListingResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ListingResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListingResponse) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

func (x *ListingResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ListingResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ListingResponse) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ListingResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListingResponse) GetPhotos() []string {
	if x != nil {
		return x.Photos
	}
	return nil
}

func (x *ListingResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ListingResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type SearchListingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	MinPrice      float64                `protobuf:"fixed64,2,opt,name=min_price,json=minPrice,proto3" json:"min_price,omitempty"`
	MaxPrice      float64                `protobuf:"fixed64,3,opt,name=max_price,json=maxPrice,proto3" json:"max_price,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`                           // Рассмотри использование enum для статуса
	CategoryId    string                 `protobuf:"bytes,5,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"` // <--- ДОБАВЛЕНО (для фильтрации по категории)
	UserId        string                 `protobuf:"bytes,6,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`             // <--- ДОБАВЛЕНО (для фильтрации по объявлениям пользователя)
	Page          int32                  `protobuf:"varint,7,opt,name=page,proto3" json:"page,omitempty"`                              // <--- ДОБАВЛЕНО (для пагинации)
	Limit         int32                  `protobuf:"varint,8,opt,name=limit,proto3" json:"limit,omitempty"`                            // <--- ДОБАВЛЕНО (для пагинации)
	SortBy        string                 `protobuf:"bytes,9,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"`             // <--- ДОБАВЛЕНО (например, "price", "created_at")
	SortOrder     string                 `protobuf:"bytes,10,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`   // <--- ДОБАВЛЕНО (например, "asc", "desc")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchListingsRequest) Reset() {
	*x = SearchListingsRequest{}
	mi := &file_api_proto_listing_listing_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchListingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchListingsRequest) ProtoMessage() {}

func (x *SearchListingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_listing_listing_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchListingsRequest.ProtoReflect.Descriptor instead.
func (*SearchListingsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_listing_listing_proto_rawDescGZIP(), []int{6}
}

func (x *SearchListingsRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchListingsRequest) GetMinPrice() float64 {
	if x != nil {
		return x.MinPrice
	}
	return 0
}

func (x *SearchListingsRequest) GetMaxPrice() float64 {
	if x != nil {
		return x.MaxPrice
	}
	return 0
}

func (x *SearchListingsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SearchListingsRequest) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

func (x *SearchListingsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SearchListingsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchListingsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SearchListingsRequest) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

func (x *SearchListingsRequest) GetSortOrder() string {
	if x != nil {
		return x.SortOrder
	}
	return ""
}

type SearchListingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Listings      []*ListingResponse     `protobuf:"bytes,1,rep,name=listings,proto3" json:"listings,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"` // <--- ДОБАВЛЕНО (общее количество найденных записей)
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`   // <--- ДОБАВЛЕНО (текущая страница)
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"` // <--- ДОБАВЛЕНО (лимит на странице)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchListingsResponse) Reset() {
	*x = SearchListingsResponse{}
	mi := &file_api_proto_listing_listing_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchListingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchListingsResponse) ProtoMessage() {}

func (x *SearchListingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_listing_listing_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchListingsResponse.ProtoReflect.Descriptor instead.
func (*SearchListingsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_listing_listing_proto_rawDescGZIP(), []int{7}
}

func (x *SearchListingsResponse) GetListings() []*ListingResponse {
	if x != nil {
		return x.Listings
	}
	return nil
}

func (x *SearchListingsResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *SearchListingsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchListingsResponse) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type UploadPhotoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ListingId     string                 `protobuf:"bytes,1,opt,name=listing_id,json=listingId,proto3" json:"listing_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // <--- ДОБАВЛЕНО (ID пользователя, загружающего фото)
	FileName      string                 `protobuf:"bytes,3,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadPhotoRequest) Reset() {
	*x = UploadPhotoRequest{}
	mi := &file_api_proto_listing_listing_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadPhotoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadPhotoRequest) ProtoMessage() {}

func (x *UploadPhotoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_listing_listing_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadPhotoRequest.ProtoReflect.Descriptor instead.
func (*UploadPhotoRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_listing_listing_proto_rawDescGZIP(), []int{8}
}

func (x *UploadPhotoRequest) GetListingId() string {
	if x != nil {
		return x.ListingId
	}
	return ""
}

func (x *UploadPhotoRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UploadPhotoRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *UploadPhotoRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type UploadPhotoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PhotoUrl      string                 `protobuf:"bytes,1,opt,name=photo_url,json=photoUrl,proto3" json:"photo_url,omitempty"` // <--- Переименовано для ясности (было url)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadPhotoResponse) Reset() {
	*x = UploadPhotoResponse{}
	mi := &file_api_proto_listing_listing_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadPhotoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadPhotoResponse) ProtoMessage() {}

func (x *UploadPhotoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_listing_listing_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadPhotoResponse.ProtoReflect.Descriptor instead.
func (*UploadPhotoResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_listing_listing_proto_rawDescGZIP(), []int{9}
}

func (x *UploadPhotoResponse) GetPhotoUrl() string {
	if x != nil {
		return x.PhotoUrl
	}
	return ""
}

// ListingStatusResponse и PhotoURLsResponse могут быть избыточны,
// если GetListingByID возвращает полный ListingResponse.
// Если они остаются, стоит добавить listing_id в ответ для контекста.
type ListingStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ListingId     string                 `protobuf:"bytes,1,opt,name=listing_id,json=listingId,proto3" json:"listing_id,omitempty"` // <--- ДОБАВЛЕНО для контекста
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListingStatusResponse) Reset() {
	*x = ListingStatusResponse{}
	mi := &file_api_proto_listing_listing_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListingStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListingStatusResponse) ProtoMessage() {}

func (x *ListingStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_listing_listing_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListingStatusResponse.ProtoReflect.Descriptor instead.
func (*ListingStatusResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_listing_listing_proto_rawDescGZIP(), []int{10}
}

func (x *ListingStatusResponse) GetListingId() string {
	if x != nil {
		return x.ListingId
	}
	return ""
}

func (x *ListingStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type AddFavoriteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ListingId     string                 `protobuf:"bytes,2,opt,name=listing_id,json=listingId,proto3" json:"listing_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddFavoriteRequest) Reset() {
	*x = AddFavoriteRequest{}
	mi := &file_api_proto_listing_listing_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddFavoriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddFavoriteRequest) ProtoMessage() {}

func (x *AddFavoriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_listing_listing_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddFavoriteRequest.ProtoReflect.Descriptor instead.
func (*AddFavoriteRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_listing_listing_proto_rawDescGZIP(), []int{11}
}

func (x *AddFavoriteRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AddFavoriteRequest) GetListingId() string {
	if x != nil {
		return x.ListingId
	}
	return ""
}

type RemoveFavoriteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ListingId     string                 `protobuf:"bytes,2,opt,name=listing_id,json=listingId,proto3" json:"listing_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveFavoriteRequest) Reset() {
	*x = RemoveFavoriteRequest{}
	mi := &file_api_proto_listing_listing_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveFavoriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFavoriteRequest) ProtoMessage() {}

func (x *RemoveFavoriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_listing_listing_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFavoriteRequest.ProtoReflect.Descriptor instead.
func (*RemoveFavoriteRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_listing_listing_proto_rawDescGZIP(), []int{12}
}

func (x *RemoveFavoriteRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RemoveFavoriteRequest) GetListingId() string {
	if x != nil {
		return x.ListingId
	}
	return ""
}

type GetFavoritesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFavoritesRequest) Reset() {
	*x = GetFavoritesRequest{}
	mi := &file_api_proto_listing_listing_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFavoritesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFavoritesRequest) ProtoMessage() {}

func (x *GetFavoritesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_listing_listing_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFavoritesRequest.ProtoReflect.Descriptor instead.
func (*GetFavoritesRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_listing_listing_proto_rawDescGZIP(), []int{13}
}

func (x *GetFavoritesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetFavoritesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ListingIds    []string               `protobuf:"bytes,1,rep,name=listing_ids,json=listingIds,proto3" json:"listing_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFavoritesResponse) Reset() {
	*x = GetFavoritesResponse{}
	mi := &file_api_proto_listing_listing_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFavoritesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFavoritesResponse) ProtoMessage() {}

func (x *GetFavoritesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_listing_listing_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFavoritesResponse.ProtoReflect.Descriptor instead.
func (*GetFavoritesResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_listing_listing_proto_rawDescGZIP(), []int{14}
}

func (x *GetFavoritesResponse) GetListingIds() []string {
	if x != nil {
		return x.ListingIds
	}
	return nil
}

type PhotoURLsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ListingId     string                 `protobuf:"bytes,1,opt,name=listing_id,json=listingId,proto3" json:"listing_id,omitempty"` // <--- ДОБАВЛЕНО для контекста
	Urls          []string               `protobuf:"bytes,2,rep,name=urls,proto3" json:"urls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PhotoURLsResponse) Reset() {
	*x = PhotoURLsResponse{}
	mi := &file_api_proto_listing_listing_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PhotoURLsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhotoURLsResponse) ProtoMessage() {}

func (x *PhotoURLsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_listing_listing_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhotoURLsResponse.ProtoReflect.Descriptor instead.
func (*PhotoURLsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_listing_listing_proto_rawDescGZIP(), []int{15}
}

func (x *PhotoURLsResponse) GetListingId() string {
	if x != nil {
		return x.ListingId
	}
	return ""
}

func (x *PhotoURLsResponse) GetUrls() []string {
	if x != nil {
		return x.Urls
	}
	return nil
}

type UpdateListingStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // <--- ДОБАВЛЕНО (ID пользователя, изменяющего статус)
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`               // Рассмотри использование enum для статуса
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateListingStatusRequest) Reset() {
	*x = UpdateListingStatusRequest{}
	mi := &file_api_proto_listing_listing_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateListingStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateListingStatusRequest) ProtoMessage() {}

func (x *UpdateListingStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_listing_listing_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateListingStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateListingStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_listing_listing_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateListingStatusRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateListingStatusRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateListingStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_api_proto_listing_listing_proto protoreflect.FileDescriptor

const file_api_proto_listing_listing_proto_rawDesc = "" +
	"\n" +
	"\x1fapi/proto/listing/listing.proto\x12\alisting\x1a\x1fgoogle/protobuf/timestamp.proto\"\a\n" +
	"\x05Empty\"\x9e\x01\n" +
	"\x14CreateListingRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1f\n" +
	"\vcategory_id\x18\x02 \x01(\tR\n" +
	"categoryId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x01R\x05price\"\xc6\x01\n" +
	"\x14UpdateListingRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1f\n" +
	"\vcategory_id\x18\x03 \x01(\tR\n" +
	"categoryId\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x06 \x01(\x01R\x05price\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\"?\n" +
	"\x14DeleteListingRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"#\n" +
	"\x11GetListingRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xcf\x02\n" +
	"\x0fListingResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1f\n" +
	"\vcategory_id\x18\x03 \x01(\tR\n" +
	"categoryId\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x06 \x01(\x01R\x05price\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12\x16\n" +
	"\x06photos\x18\b \x03(\tR\x06photos\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x9b\x02\n" +
	"\x15SearchListingsRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x1b\n" +
	"\tmin_price\x18\x02 \x01(\x01R\bminPrice\x12\x1b\n" +
	"\tmax_price\x18\x03 \x01(\x01R\bmaxPrice\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1f\n" +
	"\vcategory_id\x18\x05 \x01(\tR\n" +
	"categoryId\x12\x17\n" +
	"\auser_id\x18\x06 \x01(\tR\x06userId\x12\x12\n" +
	"\x04page\x18\a \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\b \x01(\x05R\x05limit\x12\x17\n" +
	"\asort_by\x18\t \x01(\tR\x06sortBy\x12\x1d\n" +
	"\n" +
	"sort_order\x18\n" +
	" \x01(\tR\tsortOrder\"\x8e\x01\n" +
	"\x16SearchListingsResponse\x124\n" +
	"\blistings\x18\x01 \x03(\v2\x18.listing.ListingResponseR\blistings\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"}\n" +
	"\x12UploadPhotoRequest\x12\x1d\n" +
	"\n" +
	"listing_id\x18\x01 \x01(\tR\tlistingId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\tfile_name\x18\x03 \x01(\tR\bfileName\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\"2\n" +
	"\x13UploadPhotoResponse\x12\x1b\n" +
	"\tphoto_url\x18\x01 \x01(\tR\bphotoUrl\"N\n" +
	"\x15ListingStatusResponse\x12\x1d\n" +
	"\n" +
	"listing_id\x18\x01 \x01(\tR\tlistingId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"L\n" +
	"\x12AddFavoriteRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"listing_id\x18\x02 \x01(\tR\tlistingId\"O\n" +
	"\x15RemoveFavoriteRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"listing_id\x18\x02 \x01(\tR\tlistingId\".\n" +
	"\x13GetFavoritesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"7\n" +
	"\x14GetFavoritesResponse\x12\x1f\n" +
	"\vlisting_ids\x18\x01 \x03(\tR\n" +
	"listingIds\"F\n" +
	"\x11PhotoURLsResponse\x12\x1d\n" +
	"\n" +
	"listing_id\x18\x01 \x01(\tR\tlistingId\x12\x12\n" +
	"\x04urls\x18\x02 \x03(\tR\x04urls\"]\n" +
	"\x1aUpdateListingStatusRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status2\x82\a\n" +
	"\x0eListingService\x12H\n" +
	"\rCreateListing\x12\x1d.listing.CreateListingRequest\x1a\x18.listing.ListingResponse\x12H\n" +
	"\rUpdateListing\x12\x1d.listing.UpdateListingRequest\x1a\x18.listing.ListingResponse\x12>\n" +
	"\rDeleteListing\x12\x1d.listing.DeleteListingRequest\x1a\x0e.listing.Empty\x12F\n" +
	"\x0eGetListingByID\x12\x1a.listing.GetListingRequest\x1a\x18.listing.ListingResponse\x12Q\n" +
	"\x0eSearchListings\x12\x1e.listing.SearchListingsRequest\x1a\x1f.listing.SearchListingsResponse\x12H\n" +
	"\vUploadPhoto\x12\x1b.listing.UploadPhotoRequest\x1a\x1c.listing.UploadPhotoResponse\x12N\n" +
	"\x10GetListingStatus\x12\x1a.listing.GetListingRequest\x1a\x1e.listing.ListingStatusResponse\x12:\n" +
	"\vAddFavorite\x12\x1b.listing.AddFavoriteRequest\x1a\x0e.listing.Empty\x12@\n" +
	"\x0eRemoveFavorite\x12\x1e.listing.RemoveFavoriteRequest\x1a\x0e.listing.Empty\x12K\n" +
	"\fGetFavorites\x12\x1c.listing.GetFavoritesRequest\x1a\x1d.listing.GetFavoritesResponse\x12F\n" +
	"\fGetPhotoURLs\x12\x1a.listing.GetListingRequest\x1a\x1a.listing.PhotoURLsResponse\x12T\n" +
	"\x13UpdateListingStatus\x12#.listing.UpdateListingStatusRequest\x1a\x18.listing.ListingResponseB\x1aZ\x18genproto/listing_serviceb\x06proto3"

var (
	file_api_proto_listing_listing_proto_rawDescOnce sync.Once
	file_api_proto_listing_listing_proto_rawDescData []byte
)

func file_api_proto_listing_listing_proto_rawDescGZIP() []byte {
	file_api_proto_listing_listing_proto_rawDescOnce.Do(func() {
		file_api_proto_listing_listing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_listing_listing_proto_rawDesc), len(file_api_proto_listing_listing_proto_rawDesc)))
	})
	return file_api_proto_listing_listing_proto_rawDescData
}

var file_api_proto_listing_listing_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_api_proto_listing_listing_proto_goTypes = []any{
	(*Empty)(nil),                      // 0: listing.Empty
	(*CreateListingRequest)(nil),       // 1: listing.CreateListingRequest
	(*UpdateListingRequest)(nil),       // 2: listing.UpdateListingRequest
	(*DeleteListingRequest)(nil),       // 3: listing.DeleteListingRequest
	(*GetListingRequest)(nil),          // 4: listing.GetListingRequest
	(*ListingResponse)(nil),            // 5: listing.ListingResponse
	(*SearchListingsRequest)(nil),      // 6: listing.SearchListingsRequest
	(*SearchListingsResponse)(nil),     // 7: listing.SearchListingsResponse
	(*UploadPhotoRequest)(nil),         // 8: listing.UploadPhotoRequest
	(*UploadPhotoResponse)(nil),        // 9: listing.UploadPhotoResponse
	(*ListingStatusResponse)(nil),      // 10: listing.ListingStatusResponse
	(*AddFavoriteRequest)(nil),         // 11: listing.AddFavoriteRequest
	(*RemoveFavoriteRequest)(nil),      // 12: listing.RemoveFavoriteRequest
	(*GetFavoritesRequest)(nil),        // 13: listing.GetFavoritesRequest
	(*GetFavoritesResponse)(nil),       // 14: listing.GetFavoritesResponse
	(*PhotoURLsResponse)(nil),          // 15: listing.PhotoURLsResponse
	(*UpdateListingStatusRequest)(nil), // 16: listing.UpdateListingStatusRequest
	(*timestamppb.Timestamp)(nil),      // 17: google.protobuf.Timestamp
}
var file_api_proto_listing_listing_proto_depIdxs = []int32{
	17, // 0: listing.ListingResponse.created_at:type_name -> google.protobuf.Timestamp
	17, // 1: listing.ListingResponse.updated_at:type_name -> google.protobuf.Timestamp
	5,  // 2: listing.SearchListingsResponse.listings:type_name -> listing.ListingResponse
	1,  // 3: listing.ListingService.CreateListing:input_type -> listing.CreateListingRequest
	2,  // 4: listing.ListingService.UpdateListing:input_type -> listing.UpdateListingRequest
	3,  // 5: listing.ListingService.DeleteListing:input_type -> listing.DeleteListingRequest
	4,  // 6: listing.ListingService.GetListingByID:input_type -> listing.GetListingRequest
	6,  // 7: listing.ListingService.SearchListings:input_type -> listing.SearchListingsRequest
	8,  // 8: listing.ListingService.UploadPhoto:input_type -> listing.UploadPhotoRequest
	4,  // 9: listing.ListingService.GetListingStatus:input_type -> listing.GetListingRequest
	11, // 10: listing.ListingService.AddFavorite:input_type -> listing.AddFavoriteRequest
	12, // 11: listing.ListingService.RemoveFavorite:input_type -> listing.RemoveFavoriteRequest
	13, // 12: listing.ListingService.GetFavorites:input_type -> listing.GetFavoritesRequest
	4,  // 13: listing.ListingService.GetPhotoURLs:input_type -> listing.GetListingRequest
	16, // 14: listing.ListingService.UpdateListingStatus:input_type -> listing.UpdateListingStatusRequest
	5,  // 15: listing.ListingService.CreateListing:output_type -> listing.ListingResponse
	5,  // 16: listing.ListingService.UpdateListing:output_type -> listing.ListingResponse
	0,  // 17: listing.ListingService.DeleteListing:output_type -> listing.Empty
	5,  // 18: listing.ListingService.GetListingByID:output_type -> listing.ListingResponse
	7,  // 19: listing.ListingService.SearchListings:output_type -> listing.SearchListingsResponse
	9,  // 20: listing.ListingService.UploadPhoto:output_type -> listing.UploadPhotoResponse
	10, // 21: listing.ListingService.GetListingStatus:output_type -> listing.ListingStatusResponse
	0,  // 22: listing.ListingService.AddFavorite:output_type -> listing.Empty
	0,  // 23: listing.ListingService.RemoveFavorite:output_type -> listing.Empty
	14, // 24: listing.ListingService.GetFavorites:output_type -> listing.GetFavoritesResponse
	15, // 25: listing.ListingService.GetPhotoURLs:output_type -> listing.PhotoURLsResponse
	5,  // 26: listing.ListingService.UpdateListingStatus:output_type -> listing.ListingResponse
	15, // [15:27] is the sub-list for method output_type
	3,  // [3:15] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_api_proto_listing_listing_proto_init() }
func file_api_proto_listing_listing_proto_init() {
	if File_api_proto_listing_listing_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_listing_listing_proto_rawDesc), len(file_api_proto_listing_listing_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_listing_listing_proto_goTypes,
		DependencyIndexes: file_api_proto_listing_listing_proto_depIdxs,
		MessageInfos:      file_api_proto_listing_listing_proto_msgTypes,
	}.Build()
	File_api_proto_listing_listing_proto = out.File
	file_api_proto_listing_listing_proto_goTypes = nil
	file_api_proto_listing_listing_proto_depIdxs = nil
}
