// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: service.proto

package servicepb

import (
	cart "github.com/Abdurahmanit/GroupProject/order-service/proto/cart"
	common "github.com/Abdurahmanit/GroupProject/order-service/proto/common"
	order "github.com/Abdurahmanit/GroupProject/order-service/proto/order"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddItemToCartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProductId     string                 `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddItemToCartRequest) Reset() {
	*x = AddItemToCartRequest{}
	mi := &file_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddItemToCartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddItemToCartRequest) ProtoMessage() {}

func (x *AddItemToCartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddItemToCartRequest.ProtoReflect.Descriptor instead.
func (*AddItemToCartRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{0}
}

func (x *AddItemToCartRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AddItemToCartRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *AddItemToCartRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type UpdateCartItemQuantityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProductId     string                 `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	NewQuantity   int32                  `protobuf:"varint,3,opt,name=new_quantity,json=newQuantity,proto3" json:"new_quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCartItemQuantityRequest) Reset() {
	*x = UpdateCartItemQuantityRequest{}
	mi := &file_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCartItemQuantityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCartItemQuantityRequest) ProtoMessage() {}

func (x *UpdateCartItemQuantityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCartItemQuantityRequest.ProtoReflect.Descriptor instead.
func (*UpdateCartItemQuantityRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateCartItemQuantityRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateCartItemQuantityRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *UpdateCartItemQuantityRequest) GetNewQuantity() int32 {
	if x != nil {
		return x.NewQuantity
	}
	return 0
}

type RemoveItemFromCartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProductId     string                 `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveItemFromCartRequest) Reset() {
	*x = RemoveItemFromCartRequest{}
	mi := &file_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveItemFromCartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveItemFromCartRequest) ProtoMessage() {}

func (x *RemoveItemFromCartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveItemFromCartRequest.ProtoReflect.Descriptor instead.
func (*RemoveItemFromCartRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{2}
}

func (x *RemoveItemFromCartRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RemoveItemFromCartRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

type GetCartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCartRequest) Reset() {
	*x = GetCartRequest{}
	mi := &file_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCartRequest) ProtoMessage() {}

func (x *GetCartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCartRequest.ProtoReflect.Descriptor instead.
func (*GetCartRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetCartRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ClearCartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearCartRequest) Reset() {
	*x = ClearCartRequest{}
	mi := &file_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearCartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearCartRequest) ProtoMessage() {}

func (x *ClearCartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearCartRequest.ProtoReflect.Descriptor instead.
func (*ClearCartRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{4}
}

func (x *ClearCartRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type PlaceOrderRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ShippingAddress *common.AddressProto   `protobuf:"bytes,2,opt,name=shipping_address,json=shippingAddress,proto3" json:"shipping_address,omitempty"`
	BillingAddress  *common.AddressProto   `protobuf:"bytes,3,opt,name=billing_address,json=billingAddress,proto3" json:"billing_address,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PlaceOrderRequest) Reset() {
	*x = PlaceOrderRequest{}
	mi := &file_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaceOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceOrderRequest) ProtoMessage() {}

func (x *PlaceOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceOrderRequest.ProtoReflect.Descriptor instead.
func (*PlaceOrderRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{5}
}

func (x *PlaceOrderRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PlaceOrderRequest) GetShippingAddress() *common.AddressProto {
	if x != nil {
		return x.ShippingAddress
	}
	return nil
}

func (x *PlaceOrderRequest) GetBillingAddress() *common.AddressProto {
	if x != nil {
		return x.BillingAddress
	}
	return nil
}

type GetOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderRequest) Reset() {
	*x = GetOrderRequest{}
	mi := &file_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderRequest) ProtoMessage() {}

func (x *GetOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderRequest.ProtoReflect.Descriptor instead.
func (*GetOrderRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{6}
}

func (x *GetOrderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type ListUserOrdersRequest struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	UserId        string                    `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Pagination    *common.PaginationRequest `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserOrdersRequest) Reset() {
	*x = ListUserOrdersRequest{}
	mi := &file_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserOrdersRequest) ProtoMessage() {}

func (x *ListUserOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserOrdersRequest.ProtoReflect.Descriptor instead.
func (*ListUserOrdersRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{7}
}

func (x *ListUserOrdersRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListUserOrdersRequest) GetPagination() *common.PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ListUserOrdersResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Orders        []*order.OrderProto        `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	Pagination    *common.PaginationResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserOrdersResponse) Reset() {
	*x = ListUserOrdersResponse{}
	mi := &file_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserOrdersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserOrdersResponse) ProtoMessage() {}

func (x *ListUserOrdersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserOrdersResponse.ProtoReflect.Descriptor instead.
func (*ListUserOrdersResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{8}
}

func (x *ListUserOrdersResponse) GetOrders() []*order.OrderProto {
	if x != nil {
		return x.Orders
	}
	return nil
}

func (x *ListUserOrdersResponse) GetPagination() *common.PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type CancelOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderRequest) Reset() {
	*x = CancelOrderRequest{}
	mi := &file_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderRequest) ProtoMessage() {}

func (x *CancelOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderRequest.ProtoReflect.Descriptor instead.
func (*CancelOrderRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{9}
}

func (x *CancelOrderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *CancelOrderRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UpdateOrderStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	NewStatus     order.OrderStatusProto `protobuf:"varint,2,opt,name=new_status,json=newStatus,proto3,enum=order.OrderStatusProto" json:"new_status,omitempty"`
	UpdatedById   string                 `protobuf:"bytes,3,opt,name=updated_by_id,json=updatedById,proto3" json:"updated_by_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOrderStatusRequest) Reset() {
	*x = UpdateOrderStatusRequest{}
	mi := &file_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOrderStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrderStatusRequest) ProtoMessage() {}

func (x *UpdateOrderStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrderStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateOrderStatusRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateOrderStatusRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *UpdateOrderStatusRequest) GetNewStatus() order.OrderStatusProto {
	if x != nil {
		return x.NewStatus
	}
	return order.OrderStatusProto(0)
}

func (x *UpdateOrderStatusRequest) GetUpdatedById() string {
	if x != nil {
		return x.UpdatedById
	}
	return ""
}

type ListAllOrdersAdminRequest struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	AdminId       string                    `protobuf:"bytes,1,opt,name=admin_id,json=adminId,proto3" json:"admin_id,omitempty"` // ID админа для проверки прав
	Pagination    *common.PaginationRequest `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAllOrdersAdminRequest) Reset() {
	*x = ListAllOrdersAdminRequest{}
	mi := &file_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAllOrdersAdminRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAllOrdersAdminRequest) ProtoMessage() {}

func (x *ListAllOrdersAdminRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAllOrdersAdminRequest.ProtoReflect.Descriptor instead.
func (*ListAllOrdersAdminRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{11}
}

func (x *ListAllOrdersAdminRequest) GetAdminId() string {
	if x != nil {
		return x.AdminId
	}
	return ""
}

func (x *ListAllOrdersAdminRequest) GetPagination() *common.PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ListAllOrdersAdminResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Orders        []*order.OrderProto        `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	Pagination    *common.PaginationResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAllOrdersAdminResponse) Reset() {
	*x = ListAllOrdersAdminResponse{}
	mi := &file_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAllOrdersAdminResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAllOrdersAdminResponse) ProtoMessage() {}

func (x *ListAllOrdersAdminResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAllOrdersAdminResponse.ProtoReflect.Descriptor instead.
func (*ListAllOrdersAdminResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{12}
}

func (x *ListAllOrdersAdminResponse) GetOrders() []*order.OrderProto {
	if x != nil {
		return x.Orders
	}
	return nil
}

func (x *ListAllOrdersAdminResponse) GetPagination() *common.PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type GenerateOrderReceiptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateOrderReceiptRequest) Reset() {
	*x = GenerateOrderReceiptRequest{}
	mi := &file_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateOrderReceiptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateOrderReceiptRequest) ProtoMessage() {}

func (x *GenerateOrderReceiptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateOrderReceiptRequest.ProtoReflect.Descriptor instead.
func (*GenerateOrderReceiptRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{13}
}

func (x *GenerateOrderReceiptRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *GenerateOrderReceiptRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GenerateOrderReceiptResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PdfContent    []byte                 `protobuf:"bytes,1,opt,name=pdf_content,json=pdfContent,proto3" json:"pdf_content,omitempty"`
	FileName      string                 `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateOrderReceiptResponse) Reset() {
	*x = GenerateOrderReceiptResponse{}
	mi := &file_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateOrderReceiptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateOrderReceiptResponse) ProtoMessage() {}

func (x *GenerateOrderReceiptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateOrderReceiptResponse.ProtoReflect.Descriptor instead.
func (*GenerateOrderReceiptResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{14}
}

func (x *GenerateOrderReceiptResponse) GetPdfContent() []byte {
	if x != nil {
		return x.PdfContent
	}
	return nil
}

func (x *GenerateOrderReceiptResponse) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

var File_service_proto protoreflect.FileDescriptor

const file_service_proto_rawDesc = "" +
	"\n" +
	"\rservice.proto\x12\aservice\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\fcommon.proto\x1a\x13cart_messages.proto\x1a\x14order_messages.proto\"j\n" +
	"\x14AddItemToCartRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\tR\tproductId\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity\"z\n" +
	"\x1dUpdateCartItemQuantityRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\tR\tproductId\x12!\n" +
	"\fnew_quantity\x18\x03 \x01(\x05R\vnewQuantity\"S\n" +
	"\x19RemoveItemFromCartRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\tR\tproductId\")\n" +
	"\x0eGetCartRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"+\n" +
	"\x10ClearCartRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\xac\x01\n" +
	"\x11PlaceOrderRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12?\n" +
	"\x10shipping_address\x18\x02 \x01(\v2\x14.common.AddressProtoR\x0fshippingAddress\x12=\n" +
	"\x0fbilling_address\x18\x03 \x01(\v2\x14.common.AddressProtoR\x0ebillingAddress\",\n" +
	"\x0fGetOrderRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\"k\n" +
	"\x15ListUserOrdersRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x129\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x19.common.PaginationRequestR\n" +
	"pagination\"\x7f\n" +
	"\x16ListUserOrdersResponse\x12)\n" +
	"\x06orders\x18\x01 \x03(\v2\x11.order.OrderProtoR\x06orders\x12:\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1a.common.PaginationResponseR\n" +
	"pagination\"H\n" +
	"\x12CancelOrderRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"\x91\x01\n" +
	"\x18UpdateOrderStatusRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x126\n" +
	"\n" +
	"new_status\x18\x02 \x01(\x0e2\x17.order.OrderStatusProtoR\tnewStatus\x12\"\n" +
	"\rupdated_by_id\x18\x03 \x01(\tR\vupdatedById\"q\n" +
	"\x19ListAllOrdersAdminRequest\x12\x19\n" +
	"\badmin_id\x18\x01 \x01(\tR\aadminId\x129\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x19.common.PaginationRequestR\n" +
	"pagination\"\x83\x01\n" +
	"\x1aListAllOrdersAdminResponse\x12)\n" +
	"\x06orders\x18\x01 \x03(\v2\x11.order.OrderProtoR\x06orders\x12:\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1a.common.PaginationResponseR\n" +
	"pagination\"Q\n" +
	"\x1bGenerateOrderReceiptRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"\\\n" +
	"\x1cGenerateOrderReceiptResponse\x12\x1f\n" +
	"\vpdf_content\x18\x01 \x01(\fR\n" +
	"pdfContent\x12\x1b\n" +
	"\tfile_name\x18\x02 \x01(\tR\bfileName2\xf4\x06\n" +
	"\fOrderService\x12?\n" +
	"\rAddItemToCart\x12\x1d.service.AddItemToCartRequest\x1a\x0f.cart.CartProto\x12Q\n" +
	"\x16UpdateCartItemQuantity\x12&.service.UpdateCartItemQuantityRequest\x1a\x0f.cart.CartProto\x12I\n" +
	"\x12RemoveItemFromCart\x12\".service.RemoveItemFromCartRequest\x1a\x0f.cart.CartProto\x123\n" +
	"\aGetCart\x12\x17.service.GetCartRequest\x1a\x0f.cart.CartProto\x12>\n" +
	"\tClearCart\x12\x19.service.ClearCartRequest\x1a\x16.google.protobuf.Empty\x12;\n" +
	"\n" +
	"PlaceOrder\x12\x1a.service.PlaceOrderRequest\x1a\x11.order.OrderProto\x127\n" +
	"\bGetOrder\x12\x18.service.GetOrderRequest\x1a\x11.order.OrderProto\x12Q\n" +
	"\x0eListUserOrders\x12\x1e.service.ListUserOrdersRequest\x1a\x1f.service.ListUserOrdersResponse\x12=\n" +
	"\vCancelOrder\x12\x1b.service.CancelOrderRequest\x1a\x11.order.OrderProto\x12I\n" +
	"\x11UpdateOrderStatus\x12!.service.UpdateOrderStatusRequest\x1a\x11.order.OrderProto\x12X\n" +
	"\rListAllOrders\x12\".service.ListAllOrdersAdminRequest\x1a#.service.ListAllOrdersAdminResponse\x12c\n" +
	"\x14GenerateOrderReceipt\x12$.service.GenerateOrderReceiptRequest\x1a%.service.GenerateOrderReceiptResponseBLZJgithub.com/Abdurahmanit/GroupProject/order-service/proto/service;servicepbb\x06proto3"

var (
	file_service_proto_rawDescOnce sync.Once
	file_service_proto_rawDescData []byte
)

func file_service_proto_rawDescGZIP() []byte {
	file_service_proto_rawDescOnce.Do(func() {
		file_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)))
	})
	return file_service_proto_rawDescData
}

var file_service_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_service_proto_goTypes = []any{
	(*AddItemToCartRequest)(nil),          // 0: service.AddItemToCartRequest
	(*UpdateCartItemQuantityRequest)(nil), // 1: service.UpdateCartItemQuantityRequest
	(*RemoveItemFromCartRequest)(nil),     // 2: service.RemoveItemFromCartRequest
	(*GetCartRequest)(nil),                // 3: service.GetCartRequest
	(*ClearCartRequest)(nil),              // 4: service.ClearCartRequest
	(*PlaceOrderRequest)(nil),             // 5: service.PlaceOrderRequest
	(*GetOrderRequest)(nil),               // 6: service.GetOrderRequest
	(*ListUserOrdersRequest)(nil),         // 7: service.ListUserOrdersRequest
	(*ListUserOrdersResponse)(nil),        // 8: service.ListUserOrdersResponse
	(*CancelOrderRequest)(nil),            // 9: service.CancelOrderRequest
	(*UpdateOrderStatusRequest)(nil),      // 10: service.UpdateOrderStatusRequest
	(*ListAllOrdersAdminRequest)(nil),     // 11: service.ListAllOrdersAdminRequest
	(*ListAllOrdersAdminResponse)(nil),    // 12: service.ListAllOrdersAdminResponse
	(*GenerateOrderReceiptRequest)(nil),   // 13: service.GenerateOrderReceiptRequest
	(*GenerateOrderReceiptResponse)(nil),  // 14: service.GenerateOrderReceiptResponse
	(*common.AddressProto)(nil),           // 15: common.AddressProto
	(*common.PaginationRequest)(nil),      // 16: common.PaginationRequest
	(*order.OrderProto)(nil),              // 17: order.OrderProto
	(*common.PaginationResponse)(nil),     // 18: common.PaginationResponse
	(order.OrderStatusProto)(0),           // 19: order.OrderStatusProto
	(*cart.CartProto)(nil),                // 20: cart.CartProto
	(*emptypb.Empty)(nil),                 // 21: google.protobuf.Empty
}
var file_service_proto_depIdxs = []int32{
	15, // 0: service.PlaceOrderRequest.shipping_address:type_name -> common.AddressProto
	15, // 1: service.PlaceOrderRequest.billing_address:type_name -> common.AddressProto
	16, // 2: service.ListUserOrdersRequest.pagination:type_name -> common.PaginationRequest
	17, // 3: service.ListUserOrdersResponse.orders:type_name -> order.OrderProto
	18, // 4: service.ListUserOrdersResponse.pagination:type_name -> common.PaginationResponse
	19, // 5: service.UpdateOrderStatusRequest.new_status:type_name -> order.OrderStatusProto
	16, // 6: service.ListAllOrdersAdminRequest.pagination:type_name -> common.PaginationRequest
	17, // 7: service.ListAllOrdersAdminResponse.orders:type_name -> order.OrderProto
	18, // 8: service.ListAllOrdersAdminResponse.pagination:type_name -> common.PaginationResponse
	0,  // 9: service.OrderService.AddItemToCart:input_type -> service.AddItemToCartRequest
	1,  // 10: service.OrderService.UpdateCartItemQuantity:input_type -> service.UpdateCartItemQuantityRequest
	2,  // 11: service.OrderService.RemoveItemFromCart:input_type -> service.RemoveItemFromCartRequest
	3,  // 12: service.OrderService.GetCart:input_type -> service.GetCartRequest
	4,  // 13: service.OrderService.ClearCart:input_type -> service.ClearCartRequest
	5,  // 14: service.OrderService.PlaceOrder:input_type -> service.PlaceOrderRequest
	6,  // 15: service.OrderService.GetOrder:input_type -> service.GetOrderRequest
	7,  // 16: service.OrderService.ListUserOrders:input_type -> service.ListUserOrdersRequest
	9,  // 17: service.OrderService.CancelOrder:input_type -> service.CancelOrderRequest
	10, // 18: service.OrderService.UpdateOrderStatus:input_type -> service.UpdateOrderStatusRequest
	11, // 19: service.OrderService.ListAllOrders:input_type -> service.ListAllOrdersAdminRequest
	13, // 20: service.OrderService.GenerateOrderReceipt:input_type -> service.GenerateOrderReceiptRequest
	20, // 21: service.OrderService.AddItemToCart:output_type -> cart.CartProto
	20, // 22: service.OrderService.UpdateCartItemQuantity:output_type -> cart.CartProto
	20, // 23: service.OrderService.RemoveItemFromCart:output_type -> cart.CartProto
	20, // 24: service.OrderService.GetCart:output_type -> cart.CartProto
	21, // 25: service.OrderService.ClearCart:output_type -> google.protobuf.Empty
	17, // 26: service.OrderService.PlaceOrder:output_type -> order.OrderProto
	17, // 27: service.OrderService.GetOrder:output_type -> order.OrderProto
	8,  // 28: service.OrderService.ListUserOrders:output_type -> service.ListUserOrdersResponse
	17, // 29: service.OrderService.CancelOrder:output_type -> order.OrderProto
	17, // 30: service.OrderService.UpdateOrderStatus:output_type -> order.OrderProto
	12, // 31: service.OrderService.ListAllOrders:output_type -> service.ListAllOrdersAdminResponse
	14, // 32: service.OrderService.GenerateOrderReceipt:output_type -> service.GenerateOrderReceiptResponse
	21, // [21:33] is the sub-list for method output_type
	9,  // [9:21] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_service_proto_init() }
func file_service_proto_init() {
	if File_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_proto_goTypes,
		DependencyIndexes: file_service_proto_depIdxs,
		MessageInfos:      file_service_proto_msgTypes,
	}.Build()
	File_service_proto = out.File
	file_service_proto_goTypes = nil
	file_service_proto_depIdxs = nil
}
