// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: service.proto

package newspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_service_proto protoreflect.FileDescriptor

const file_service_proto_rawDesc = "" +
	"\n" +
	"\rservice.proto\x12\x04news\x1a\n" +
	"news.proto\x1a\rcomment.proto\x1a\n" +
	"like.proto2\xc5\x06\n" +
	"\vNewsService\x12?\n" +
	"\n" +
	"CreateNews\x12\x17.news.CreateNewsRequest\x1a\x18.news.CreateNewsResponse\x126\n" +
	"\aGetNews\x12\x14.news.GetNewsRequest\x1a\x15.news.GetNewsResponse\x129\n" +
	"\bListNews\x12\x15.news.ListNewsRequest\x1a\x16.news.ListNewsResponse\x12?\n" +
	"\n" +
	"UpdateNews\x12\x17.news.UpdateNewsRequest\x1a\x18.news.UpdateNewsResponse\x12?\n" +
	"\n" +
	"DeleteNews\x12\x17.news.DeleteNewsRequest\x1a\x18.news.DeleteNewsResponse\x12H\n" +
	"\rCreateComment\x12\x1a.news.CreateCommentRequest\x1a\x1b.news.CreateCommentResponse\x12W\n" +
	"\x12GetCommentsForNews\x12\x1f.news.GetCommentsForNewsRequest\x1a .news.GetCommentsForNewsResponse\x12H\n" +
	"\rDeleteComment\x12\x1a.news.DeleteCommentRequest\x1a\x1b.news.DeleteCommentResponse\x129\n" +
	"\bLikeNews\x12\x15.news.LikeNewsRequest\x1a\x16.news.LikeNewsResponse\x12?\n" +
	"\n" +
	"UnlikeNews\x12\x17.news.UnlikeNewsRequest\x1a\x18.news.UnlikeNewsResponse\x12H\n" +
	"\rGetLikesCount\x12\x1a.news.GetLikesCountRequest\x1a\x1b.news.GetLikesCountResponse\x12M\n" +
	"\x12ListNewsByCategory\x12\x1f.news.ListNewsByCategoryRequest\x1a\x16.news.ListNewsResponseB@Z>github.com/Abdurahmanit/GroupProject/news-service/proto;newspbb\x06proto3"

var file_service_proto_goTypes = []any{
	(*CreateNewsRequest)(nil),          // 0: news.CreateNewsRequest
	(*GetNewsRequest)(nil),             // 1: news.GetNewsRequest
	(*ListNewsRequest)(nil),            // 2: news.ListNewsRequest
	(*UpdateNewsRequest)(nil),          // 3: news.UpdateNewsRequest
	(*DeleteNewsRequest)(nil),          // 4: news.DeleteNewsRequest
	(*CreateCommentRequest)(nil),       // 5: news.CreateCommentRequest
	(*GetCommentsForNewsRequest)(nil),  // 6: news.GetCommentsForNewsRequest
	(*DeleteCommentRequest)(nil),       // 7: news.DeleteCommentRequest
	(*LikeNewsRequest)(nil),            // 8: news.LikeNewsRequest
	(*UnlikeNewsRequest)(nil),          // 9: news.UnlikeNewsRequest
	(*GetLikesCountRequest)(nil),       // 10: news.GetLikesCountRequest
	(*ListNewsByCategoryRequest)(nil),  // 11: news.ListNewsByCategoryRequest
	(*CreateNewsResponse)(nil),         // 12: news.CreateNewsResponse
	(*GetNewsResponse)(nil),            // 13: news.GetNewsResponse
	(*ListNewsResponse)(nil),           // 14: news.ListNewsResponse
	(*UpdateNewsResponse)(nil),         // 15: news.UpdateNewsResponse
	(*DeleteNewsResponse)(nil),         // 16: news.DeleteNewsResponse
	(*CreateCommentResponse)(nil),      // 17: news.CreateCommentResponse
	(*GetCommentsForNewsResponse)(nil), // 18: news.GetCommentsForNewsResponse
	(*DeleteCommentResponse)(nil),      // 19: news.DeleteCommentResponse
	(*LikeNewsResponse)(nil),           // 20: news.LikeNewsResponse
	(*UnlikeNewsResponse)(nil),         // 21: news.UnlikeNewsResponse
	(*GetLikesCountResponse)(nil),      // 22: news.GetLikesCountResponse
}
var file_service_proto_depIdxs = []int32{
	0,  // 0: news.NewsService.CreateNews:input_type -> news.CreateNewsRequest
	1,  // 1: news.NewsService.GetNews:input_type -> news.GetNewsRequest
	2,  // 2: news.NewsService.ListNews:input_type -> news.ListNewsRequest
	3,  // 3: news.NewsService.UpdateNews:input_type -> news.UpdateNewsRequest
	4,  // 4: news.NewsService.DeleteNews:input_type -> news.DeleteNewsRequest
	5,  // 5: news.NewsService.CreateComment:input_type -> news.CreateCommentRequest
	6,  // 6: news.NewsService.GetCommentsForNews:input_type -> news.GetCommentsForNewsRequest
	7,  // 7: news.NewsService.DeleteComment:input_type -> news.DeleteCommentRequest
	8,  // 8: news.NewsService.LikeNews:input_type -> news.LikeNewsRequest
	9,  // 9: news.NewsService.UnlikeNews:input_type -> news.UnlikeNewsRequest
	10, // 10: news.NewsService.GetLikesCount:input_type -> news.GetLikesCountRequest
	11, // 11: news.NewsService.ListNewsByCategory:input_type -> news.ListNewsByCategoryRequest
	12, // 12: news.NewsService.CreateNews:output_type -> news.CreateNewsResponse
	13, // 13: news.NewsService.GetNews:output_type -> news.GetNewsResponse
	14, // 14: news.NewsService.ListNews:output_type -> news.ListNewsResponse
	15, // 15: news.NewsService.UpdateNews:output_type -> news.UpdateNewsResponse
	16, // 16: news.NewsService.DeleteNews:output_type -> news.DeleteNewsResponse
	17, // 17: news.NewsService.CreateComment:output_type -> news.CreateCommentResponse
	18, // 18: news.NewsService.GetCommentsForNews:output_type -> news.GetCommentsForNewsResponse
	19, // 19: news.NewsService.DeleteComment:output_type -> news.DeleteCommentResponse
	20, // 20: news.NewsService.LikeNews:output_type -> news.LikeNewsResponse
	21, // 21: news.NewsService.UnlikeNews:output_type -> news.UnlikeNewsResponse
	22, // 22: news.NewsService.GetLikesCount:output_type -> news.GetLikesCountResponse
	14, // 23: news.NewsService.ListNewsByCategory:output_type -> news.ListNewsResponse
	12, // [12:24] is the sub-list for method output_type
	0,  // [0:12] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_service_proto_init() }
func file_service_proto_init() {
	if File_service_proto != nil {
		return
	}
	file_news_proto_init()
	file_comment_proto_init()
	file_like_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_proto_goTypes,
		DependencyIndexes: file_service_proto_depIdxs,
	}.Build()
	File_service_proto = out.File
	file_service_proto_goTypes = nil
	file_service_proto_depIdxs = nil
}
