// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: service.proto

package newspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetNewsByAuthorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthorId      string                 `protobuf:"bytes,1,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNewsByAuthorRequest) Reset() {
	*x = GetNewsByAuthorRequest{}
	mi := &file_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNewsByAuthorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNewsByAuthorRequest) ProtoMessage() {}

func (x *GetNewsByAuthorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNewsByAuthorRequest.ProtoReflect.Descriptor instead.
func (*GetNewsByAuthorRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetNewsByAuthorRequest) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

func (x *GetNewsByAuthorRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetNewsByAuthorRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

var File_service_proto protoreflect.FileDescriptor

const file_service_proto_rawDesc = "" +
	"\n" +
	"\rservice.proto\x12\x04news\x1a\n" +
	"news.proto\x1a\rcomment.proto\x1a\n" +
	"like.proto\"f\n" +
	"\x16GetNewsByAuthorRequest\x12\x1b\n" +
	"\tauthor_id\x18\x01 \x01(\tR\bauthorId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize2\xbf\x06\n" +
	"\vNewsService\x12?\n" +
	"\n" +
	"CreateNews\x12\x17.news.CreateNewsRequest\x1a\x18.news.CreateNewsResponse\x126\n" +
	"\aGetNews\x12\x14.news.GetNewsRequest\x1a\x15.news.GetNewsResponse\x129\n" +
	"\bListNews\x12\x15.news.ListNewsRequest\x1a\x16.news.ListNewsResponse\x12?\n" +
	"\n" +
	"UpdateNews\x12\x17.news.UpdateNewsRequest\x1a\x18.news.UpdateNewsResponse\x12?\n" +
	"\n" +
	"DeleteNews\x12\x17.news.DeleteNewsRequest\x1a\x18.news.DeleteNewsResponse\x12H\n" +
	"\rCreateComment\x12\x1a.news.CreateCommentRequest\x1a\x1b.news.CreateCommentResponse\x12W\n" +
	"\x12GetCommentsForNews\x12\x1f.news.GetCommentsForNewsRequest\x1a .news.GetCommentsForNewsResponse\x12H\n" +
	"\rDeleteComment\x12\x1a.news.DeleteCommentRequest\x1a\x1b.news.DeleteCommentResponse\x129\n" +
	"\bLikeNews\x12\x15.news.LikeNewsRequest\x1a\x16.news.LikeNewsResponse\x12?\n" +
	"\n" +
	"UnlikeNews\x12\x17.news.UnlikeNewsRequest\x1a\x18.news.UnlikeNewsResponse\x12H\n" +
	"\rGetLikesCount\x12\x1a.news.GetLikesCountRequest\x1a\x1b.news.GetLikesCountResponse\x12G\n" +
	"\x0fGetNewsByAuthor\x12\x1c.news.GetNewsByAuthorRequest\x1a\x16.news.ListNewsResponseB@Z>github.com/Abdurahmanit/GroupProject/news-service/proto;newspbb\x06proto3"

var (
	file_service_proto_rawDescOnce sync.Once
	file_service_proto_rawDescData []byte
)

func file_service_proto_rawDescGZIP() []byte {
	file_service_proto_rawDescOnce.Do(func() {
		file_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)))
	})
	return file_service_proto_rawDescData
}

var file_service_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_service_proto_goTypes = []any{
	(*GetNewsByAuthorRequest)(nil),     // 0: news.GetNewsByAuthorRequest
	(*CreateNewsRequest)(nil),          // 1: news.CreateNewsRequest
	(*GetNewsRequest)(nil),             // 2: news.GetNewsRequest
	(*ListNewsRequest)(nil),            // 3: news.ListNewsRequest
	(*UpdateNewsRequest)(nil),          // 4: news.UpdateNewsRequest
	(*DeleteNewsRequest)(nil),          // 5: news.DeleteNewsRequest
	(*CreateCommentRequest)(nil),       // 6: news.CreateCommentRequest
	(*GetCommentsForNewsRequest)(nil),  // 7: news.GetCommentsForNewsRequest
	(*DeleteCommentRequest)(nil),       // 8: news.DeleteCommentRequest
	(*LikeNewsRequest)(nil),            // 9: news.LikeNewsRequest
	(*UnlikeNewsRequest)(nil),          // 10: news.UnlikeNewsRequest
	(*GetLikesCountRequest)(nil),       // 11: news.GetLikesCountRequest
	(*CreateNewsResponse)(nil),         // 12: news.CreateNewsResponse
	(*GetNewsResponse)(nil),            // 13: news.GetNewsResponse
	(*ListNewsResponse)(nil),           // 14: news.ListNewsResponse
	(*UpdateNewsResponse)(nil),         // 15: news.UpdateNewsResponse
	(*DeleteNewsResponse)(nil),         // 16: news.DeleteNewsResponse
	(*CreateCommentResponse)(nil),      // 17: news.CreateCommentResponse
	(*GetCommentsForNewsResponse)(nil), // 18: news.GetCommentsForNewsResponse
	(*DeleteCommentResponse)(nil),      // 19: news.DeleteCommentResponse
	(*LikeNewsResponse)(nil),           // 20: news.LikeNewsResponse
	(*UnlikeNewsResponse)(nil),         // 21: news.UnlikeNewsResponse
	(*GetLikesCountResponse)(nil),      // 22: news.GetLikesCountResponse
}
var file_service_proto_depIdxs = []int32{
	1,  // 0: news.NewsService.CreateNews:input_type -> news.CreateNewsRequest
	2,  // 1: news.NewsService.GetNews:input_type -> news.GetNewsRequest
	3,  // 2: news.NewsService.ListNews:input_type -> news.ListNewsRequest
	4,  // 3: news.NewsService.UpdateNews:input_type -> news.UpdateNewsRequest
	5,  // 4: news.NewsService.DeleteNews:input_type -> news.DeleteNewsRequest
	6,  // 5: news.NewsService.CreateComment:input_type -> news.CreateCommentRequest
	7,  // 6: news.NewsService.GetCommentsForNews:input_type -> news.GetCommentsForNewsRequest
	8,  // 7: news.NewsService.DeleteComment:input_type -> news.DeleteCommentRequest
	9,  // 8: news.NewsService.LikeNews:input_type -> news.LikeNewsRequest
	10, // 9: news.NewsService.UnlikeNews:input_type -> news.UnlikeNewsRequest
	11, // 10: news.NewsService.GetLikesCount:input_type -> news.GetLikesCountRequest
	0,  // 11: news.NewsService.GetNewsByAuthor:input_type -> news.GetNewsByAuthorRequest
	12, // 12: news.NewsService.CreateNews:output_type -> news.CreateNewsResponse
	13, // 13: news.NewsService.GetNews:output_type -> news.GetNewsResponse
	14, // 14: news.NewsService.ListNews:output_type -> news.ListNewsResponse
	15, // 15: news.NewsService.UpdateNews:output_type -> news.UpdateNewsResponse
	16, // 16: news.NewsService.DeleteNews:output_type -> news.DeleteNewsResponse
	17, // 17: news.NewsService.CreateComment:output_type -> news.CreateCommentResponse
	18, // 18: news.NewsService.GetCommentsForNews:output_type -> news.GetCommentsForNewsResponse
	19, // 19: news.NewsService.DeleteComment:output_type -> news.DeleteCommentResponse
	20, // 20: news.NewsService.LikeNews:output_type -> news.LikeNewsResponse
	21, // 21: news.NewsService.UnlikeNews:output_type -> news.UnlikeNewsResponse
	22, // 22: news.NewsService.GetLikesCount:output_type -> news.GetLikesCountResponse
	14, // 23: news.NewsService.GetNewsByAuthor:output_type -> news.ListNewsResponse
	12, // [12:24] is the sub-list for method output_type
	0,  // [0:12] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_service_proto_init() }
func file_service_proto_init() {
	if File_service_proto != nil {
		return
	}
	file_news_proto_init()
	file_comment_proto_init()
	file_like_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_proto_goTypes,
		DependencyIndexes: file_service_proto_depIdxs,
		MessageInfos:      file_service_proto_msgTypes,
	}.Build()
	File_service_proto = out.File
	file_service_proto_goTypes = nil
	file_service_proto_depIdxs = nil
}
