# docker-compose.yml
version: '3.8'
services:
  mongo1:
    image: mongo:6.0
    container_name: mongo1
    ports:
      - "27017:27017"
    volumes:
      - mongo1_data:/data/db
    command: ["--replSet", "rs0", "--bind_ip_all"]
    healthcheck:
      test: echo 'try { rs.status() } catch (err) { rs.initiate({_id:"rs0",members:[{_id:0,host:"mongo1:27017"}]}) }' | mongosh --quiet
      interval: 5s
      timeout: 30s
      start_period: 5s
      retries: 20

volumes:
  mongo1_data: