// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: cart_messages.proto

package cartpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CartItemProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	ProductName   string                 `protobuf:"bytes,3,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`
	PricePerUnit  float64                `protobuf:"fixed64,4,opt,name=price_per_unit,json=pricePerUnit,proto3" json:"price_per_unit,omitempty"`
	TotalPrice    float64                `protobuf:"fixed64,5,opt,name=total_price,json=totalPrice,proto3" json:"total_price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CartItemProto) Reset() {
	*x = CartItemProto{}
	mi := &file_cart_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartItemProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartItemProto) ProtoMessage() {}

func (x *CartItemProto) ProtoReflect() protoreflect.Message {
	mi := &file_cart_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartItemProto.ProtoReflect.Descriptor instead.
func (*CartItemProto) Descriptor() ([]byte, []int) {
	return file_cart_messages_proto_rawDescGZIP(), []int{0}
}

func (x *CartItemProto) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *CartItemProto) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *CartItemProto) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *CartItemProto) GetPricePerUnit() float64 {
	if x != nil {
		return x.PricePerUnit
	}
	return 0
}

func (x *CartItemProto) GetTotalPrice() float64 {
	if x != nil {
		return x.TotalPrice
	}
	return 0
}

type CartProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Items         []*CartItemProto       `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	TotalAmount   float64                `protobuf:"fixed64,3,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CartProto) Reset() {
	*x = CartProto{}
	mi := &file_cart_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartProto) ProtoMessage() {}

func (x *CartProto) ProtoReflect() protoreflect.Message {
	mi := &file_cart_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartProto.ProtoReflect.Descriptor instead.
func (*CartProto) Descriptor() ([]byte, []int) {
	return file_cart_messages_proto_rawDescGZIP(), []int{1}
}

func (x *CartProto) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CartProto) GetItems() []*CartItemProto {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *CartProto) GetTotalAmount() float64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

var File_cart_messages_proto protoreflect.FileDescriptor

const file_cart_messages_proto_rawDesc = "" +
	"\n" +
	"\x13cart_messages.proto\x12\x04cart\"\xb4\x01\n" +
	"\rCartItemProto\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\x12!\n" +
	"\fproduct_name\x18\x03 \x01(\tR\vproductName\x12$\n" +
	"\x0eprice_per_unit\x18\x04 \x01(\x01R\fpricePerUnit\x12\x1f\n" +
	"\vtotal_price\x18\x05 \x01(\x01R\n" +
	"totalPrice\"r\n" +
	"\tCartProto\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12)\n" +
	"\x05items\x18\x02 \x03(\v2\x13.cart.CartItemProtoR\x05items\x12!\n" +
	"\ftotal_amount\x18\x03 \x01(\x01R\vtotalAmountBFZDgithub.com/Abdurahmanit/GroupProject/order-service/proto/cart;cartpbb\x06proto3"

var (
	file_cart_messages_proto_rawDescOnce sync.Once
	file_cart_messages_proto_rawDescData []byte
)

func file_cart_messages_proto_rawDescGZIP() []byte {
	file_cart_messages_proto_rawDescOnce.Do(func() {
		file_cart_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cart_messages_proto_rawDesc), len(file_cart_messages_proto_rawDesc)))
	})
	return file_cart_messages_proto_rawDescData
}

var file_cart_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_cart_messages_proto_goTypes = []any{
	(*CartItemProto)(nil), // 0: cart.CartItemProto
	(*CartProto)(nil),     // 1: cart.CartProto
}
var file_cart_messages_proto_depIdxs = []int32{
	0, // 0: cart.CartProto.items:type_name -> cart.CartItemProto
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_cart_messages_proto_init() }
func file_cart_messages_proto_init() {
	if File_cart_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cart_messages_proto_rawDesc), len(file_cart_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cart_messages_proto_goTypes,
		DependencyIndexes: file_cart_messages_proto_depIdxs,
		MessageInfos:      file_cart_messages_proto_msgTypes,
	}.Build()
	File_cart_messages_proto = out.File
	file_cart_messages_proto_goTypes = nil
	file_cart_messages_proto_depIdxs = nil
}
