// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: order_messages.proto

package orderpb

import (
	common "github.com/Abdurahmanit/GroupProject/order-service/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderStatusProto int32

const (
	OrderStatusProto_ORDER_STATUS_PROTO_UNSPECIFIED OrderStatusProto = 0
	OrderStatusProto_PENDING_PAYMENT                OrderStatusProto = 1
	OrderStatusProto_PAID                           OrderStatusProto = 2
	OrderStatusProto_PROCESSING                     OrderStatusProto = 3
	OrderStatusProto_SHIPPED                        OrderStatusProto = 4
	OrderStatusProto_DELIVERED                      OrderStatusProto = 5
	OrderStatusProto_CANCELLED                      OrderStatusProto = 6
	OrderStatusProto_FAILED                         OrderStatusProto = 7
)

// Enum value maps for OrderStatusProto.
var (
	OrderStatusProto_name = map[int32]string{
		0: "ORDER_STATUS_PROTO_UNSPECIFIED",
		1: "PENDING_PAYMENT",
		2: "PAID",
		3: "PROCESSING",
		4: "SHIPPED",
		5: "DELIVERED",
		6: "CANCELLED",
		7: "FAILED",
	}
	OrderStatusProto_value = map[string]int32{
		"ORDER_STATUS_PROTO_UNSPECIFIED": 0,
		"PENDING_PAYMENT":                1,
		"PAID":                           2,
		"PROCESSING":                     3,
		"SHIPPED":                        4,
		"DELIVERED":                      5,
		"CANCELLED":                      6,
		"FAILED":                         7,
	}
)

func (x OrderStatusProto) Enum() *OrderStatusProto {
	p := new(OrderStatusProto)
	*p = x
	return p
}

func (x OrderStatusProto) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderStatusProto) Descriptor() protoreflect.EnumDescriptor {
	return file_order_messages_proto_enumTypes[0].Descriptor()
}

func (OrderStatusProto) Type() protoreflect.EnumType {
	return &file_order_messages_proto_enumTypes[0]
}

func (x OrderStatusProto) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderStatusProto.Descriptor instead.
func (OrderStatusProto) EnumDescriptor() ([]byte, []int) {
	return file_order_messages_proto_rawDescGZIP(), []int{0}
}

type OrderItemProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ProductName   string                 `protobuf:"bytes,2,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`
	Quantity      int32                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	PricePerUnit  float64                `protobuf:"fixed64,4,opt,name=price_per_unit,json=pricePerUnit,proto3" json:"price_per_unit,omitempty"`
	TotalPrice    float64                `protobuf:"fixed64,5,opt,name=total_price,json=totalPrice,proto3" json:"total_price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderItemProto) Reset() {
	*x = OrderItemProto{}
	mi := &file_order_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItemProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItemProto) ProtoMessage() {}

func (x *OrderItemProto) ProtoReflect() protoreflect.Message {
	mi := &file_order_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItemProto.ProtoReflect.Descriptor instead.
func (*OrderItemProto) Descriptor() ([]byte, []int) {
	return file_order_messages_proto_rawDescGZIP(), []int{0}
}

func (x *OrderItemProto) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *OrderItemProto) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *OrderItemProto) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *OrderItemProto) GetPricePerUnit() float64 {
	if x != nil {
		return x.PricePerUnit
	}
	return 0
}

func (x *OrderItemProto) GetTotalPrice() float64 {
	if x != nil {
		return x.TotalPrice
	}
	return 0
}

type PaymentDetailsProto struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PaymentMethodId string                 `protobuf:"bytes,1,opt,name=payment_method_id,json=paymentMethodId,proto3" json:"payment_method_id,omitempty"`
	TransactionId   string                 `protobuf:"bytes,2,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	PaymentStatus   string                 `protobuf:"bytes,3,opt,name=payment_status,json=paymentStatus,proto3" json:"payment_status,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PaymentDetailsProto) Reset() {
	*x = PaymentDetailsProto{}
	mi := &file_order_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentDetailsProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentDetailsProto) ProtoMessage() {}

func (x *PaymentDetailsProto) ProtoReflect() protoreflect.Message {
	mi := &file_order_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentDetailsProto.ProtoReflect.Descriptor instead.
func (*PaymentDetailsProto) Descriptor() ([]byte, []int) {
	return file_order_messages_proto_rawDescGZIP(), []int{1}
}

func (x *PaymentDetailsProto) GetPaymentMethodId() string {
	if x != nil {
		return x.PaymentMethodId
	}
	return ""
}

func (x *PaymentDetailsProto) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *PaymentDetailsProto) GetPaymentStatus() string {
	if x != nil {
		return x.PaymentStatus
	}
	return ""
}

type OrderProto struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId          string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Items           []*OrderItemProto      `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	TotalAmount     float64                `protobuf:"fixed64,4,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	Status          OrderStatusProto       `protobuf:"varint,5,opt,name=status,proto3,enum=order.OrderStatusProto" json:"status,omitempty"`
	ShippingAddress *common.AddressProto   `protobuf:"bytes,6,opt,name=shipping_address,json=shippingAddress,proto3" json:"shipping_address,omitempty"`
	BillingAddress  *common.AddressProto   `protobuf:"bytes,7,opt,name=billing_address,json=billingAddress,proto3" json:"billing_address,omitempty"`
	PaymentDetails  *PaymentDetailsProto   `protobuf:"bytes,8,opt,name=payment_details,json=paymentDetails,proto3" json:"payment_details,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *OrderProto) Reset() {
	*x = OrderProto{}
	mi := &file_order_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderProto) ProtoMessage() {}

func (x *OrderProto) ProtoReflect() protoreflect.Message {
	mi := &file_order_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderProto.ProtoReflect.Descriptor instead.
func (*OrderProto) Descriptor() ([]byte, []int) {
	return file_order_messages_proto_rawDescGZIP(), []int{2}
}

func (x *OrderProto) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OrderProto) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *OrderProto) GetItems() []*OrderItemProto {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *OrderProto) GetTotalAmount() float64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *OrderProto) GetStatus() OrderStatusProto {
	if x != nil {
		return x.Status
	}
	return OrderStatusProto_ORDER_STATUS_PROTO_UNSPECIFIED
}

func (x *OrderProto) GetShippingAddress() *common.AddressProto {
	if x != nil {
		return x.ShippingAddress
	}
	return nil
}

func (x *OrderProto) GetBillingAddress() *common.AddressProto {
	if x != nil {
		return x.BillingAddress
	}
	return nil
}

func (x *OrderProto) GetPaymentDetails() *PaymentDetailsProto {
	if x != nil {
		return x.PaymentDetails
	}
	return nil
}

func (x *OrderProto) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *OrderProto) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_order_messages_proto protoreflect.FileDescriptor

const file_order_messages_proto_rawDesc = "" +
	"\n" +
	"\x14order_messages.proto\x12\x05order\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\fcommon.proto\"\xb5\x01\n" +
	"\x0eOrderItemProto\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12!\n" +
	"\fproduct_name\x18\x02 \x01(\tR\vproductName\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity\x12$\n" +
	"\x0eprice_per_unit\x18\x04 \x01(\x01R\fpricePerUnit\x12\x1f\n" +
	"\vtotal_price\x18\x05 \x01(\x01R\n" +
	"totalPrice\"\x8f\x01\n" +
	"\x13PaymentDetailsProto\x12*\n" +
	"\x11payment_method_id\x18\x01 \x01(\tR\x0fpaymentMethodId\x12%\n" +
	"\x0etransaction_id\x18\x02 \x01(\tR\rtransactionId\x12%\n" +
	"\x0epayment_status\x18\x03 \x01(\tR\rpaymentStatus\"\xf1\x03\n" +
	"\n" +
	"OrderProto\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12+\n" +
	"\x05items\x18\x03 \x03(\v2\x15.order.OrderItemProtoR\x05items\x12!\n" +
	"\ftotal_amount\x18\x04 \x01(\x01R\vtotalAmount\x12/\n" +
	"\x06status\x18\x05 \x01(\x0e2\x17.order.OrderStatusProtoR\x06status\x12?\n" +
	"\x10shipping_address\x18\x06 \x01(\v2\x14.common.AddressProtoR\x0fshippingAddress\x12=\n" +
	"\x0fbilling_address\x18\a \x01(\v2\x14.common.AddressProtoR\x0ebillingAddress\x12C\n" +
	"\x0fpayment_details\x18\b \x01(\v2\x1a.order.PaymentDetailsProtoR\x0epaymentDetails\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt*\x9c\x01\n" +
	"\x10OrderStatusProto\x12\"\n" +
	"\x1eORDER_STATUS_PROTO_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fPENDING_PAYMENT\x10\x01\x12\b\n" +
	"\x04PAID\x10\x02\x12\x0e\n" +
	"\n" +
	"PROCESSING\x10\x03\x12\v\n" +
	"\aSHIPPED\x10\x04\x12\r\n" +
	"\tDELIVERED\x10\x05\x12\r\n" +
	"\tCANCELLED\x10\x06\x12\n" +
	"\n" +
	"\x06FAILED\x10\aBHZFgithub.com/Abdurahmanit/GroupProject/order-service/proto/order;orderpbb\x06proto3"

var (
	file_order_messages_proto_rawDescOnce sync.Once
	file_order_messages_proto_rawDescData []byte
)

func file_order_messages_proto_rawDescGZIP() []byte {
	file_order_messages_proto_rawDescOnce.Do(func() {
		file_order_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_order_messages_proto_rawDesc), len(file_order_messages_proto_rawDesc)))
	})
	return file_order_messages_proto_rawDescData
}

var file_order_messages_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_order_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_order_messages_proto_goTypes = []any{
	(OrderStatusProto)(0),         // 0: order.OrderStatusProto
	(*OrderItemProto)(nil),        // 1: order.OrderItemProto
	(*PaymentDetailsProto)(nil),   // 2: order.PaymentDetailsProto
	(*OrderProto)(nil),            // 3: order.OrderProto
	(*common.AddressProto)(nil),   // 4: common.AddressProto
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_order_messages_proto_depIdxs = []int32{
	1, // 0: order.OrderProto.items:type_name -> order.OrderItemProto
	0, // 1: order.OrderProto.status:type_name -> order.OrderStatusProto
	4, // 2: order.OrderProto.shipping_address:type_name -> common.AddressProto
	4, // 3: order.OrderProto.billing_address:type_name -> common.AddressProto
	2, // 4: order.OrderProto.payment_details:type_name -> order.PaymentDetailsProto
	5, // 5: order.OrderProto.created_at:type_name -> google.protobuf.Timestamp
	5, // 6: order.OrderProto.updated_at:type_name -> google.protobuf.Timestamp
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_order_messages_proto_init() }
func file_order_messages_proto_init() {
	if File_order_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_messages_proto_rawDesc), len(file_order_messages_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_order_messages_proto_goTypes,
		DependencyIndexes: file_order_messages_proto_depIdxs,
		EnumInfos:         file_order_messages_proto_enumTypes,
		MessageInfos:      file_order_messages_proto_msgTypes,
	}.Build()
	File_order_messages_proto = out.File
	file_order_messages_proto_goTypes = nil
	file_order_messages_proto_depIdxs = nil
}
